# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.31.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.31.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/anavalle/Documents/ProyectoDeimos2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/anavalle/Documents/ProyectoDeimos2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.31.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anavalle/Documents/ProyectoDeimos2/CMakeFiles /Users/anavalle/Documents/ProyectoDeimos2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anavalle/Documents/ProyectoDeimos2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProyectDeimos2

# Build rule for target.
ProyectDeimos2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProyectDeimos2
.PHONY : ProyectDeimos2

# fast build rule for target.
ProyectDeimos2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/build
.PHONY : ProyectDeimos2/fast

#=============================================================================
# Target rules for targets named ProyectDeimos2_autogen_timestamp_deps

# Build rule for target.
ProyectDeimos2_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProyectDeimos2_autogen_timestamp_deps
.PHONY : ProyectDeimos2_autogen_timestamp_deps

# fast build rule for target.
ProyectDeimos2_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2_autogen_timestamp_deps.dir/build.make CMakeFiles/ProyectDeimos2_autogen_timestamp_deps.dir/build
.PHONY : ProyectDeimos2_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ProyectDeimos2_autogen

# Build rule for target.
ProyectDeimos2_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProyectDeimos2_autogen
.PHONY : ProyectDeimos2_autogen

# fast build rule for target.
ProyectDeimos2_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2_autogen.dir/build.make CMakeFiles/ProyectDeimos2_autogen.dir/build
.PHONY : ProyectDeimos2_autogen/fast

ObjetosYColisiones.o: ObjetosYColisiones.cpp.o
.PHONY : ObjetosYColisiones.o

# target to build an object file
ObjetosYColisiones.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ObjetosYColisiones.cpp.o
.PHONY : ObjetosYColisiones.cpp.o

ObjetosYColisiones.i: ObjetosYColisiones.cpp.i
.PHONY : ObjetosYColisiones.i

# target to preprocess a source file
ObjetosYColisiones.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ObjetosYColisiones.cpp.i
.PHONY : ObjetosYColisiones.cpp.i

ObjetosYColisiones.s: ObjetosYColisiones.cpp.s
.PHONY : ObjetosYColisiones.s

# target to generate assembly for a file
ObjetosYColisiones.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ObjetosYColisiones.cpp.s
.PHONY : ObjetosYColisiones.cpp.s

ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.o: ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.o

# target to build an object file
ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.o

ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.i: ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.i

ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.s: ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.cpp.s

ProyectDeimos2_autogen/mocs_compilation.o: ProyectDeimos2_autogen/mocs_compilation.cpp.o
.PHONY : ProyectDeimos2_autogen/mocs_compilation.o

# target to build an object file
ProyectDeimos2_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ProyectDeimos2_autogen/mocs_compilation.cpp.o
.PHONY : ProyectDeimos2_autogen/mocs_compilation.cpp.o

ProyectDeimos2_autogen/mocs_compilation.i: ProyectDeimos2_autogen/mocs_compilation.cpp.i
.PHONY : ProyectDeimos2_autogen/mocs_compilation.i

# target to preprocess a source file
ProyectDeimos2_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ProyectDeimos2_autogen/mocs_compilation.cpp.i
.PHONY : ProyectDeimos2_autogen/mocs_compilation.cpp.i

ProyectDeimos2_autogen/mocs_compilation.s: ProyectDeimos2_autogen/mocs_compilation.cpp.s
.PHONY : ProyectDeimos2_autogen/mocs_compilation.s

# target to generate assembly for a file
ProyectDeimos2_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/ProyectDeimos2_autogen/mocs_compilation.cpp.s
.PHONY : ProyectDeimos2_autogen/mocs_compilation.cpp.s

clickablelabel.o: clickablelabel.cpp.o
.PHONY : clickablelabel.o

# target to build an object file
clickablelabel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/clickablelabel.cpp.o
.PHONY : clickablelabel.cpp.o

clickablelabel.i: clickablelabel.cpp.i
.PHONY : clickablelabel.i

# target to preprocess a source file
clickablelabel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/clickablelabel.cpp.i
.PHONY : clickablelabel.cpp.i

clickablelabel.s: clickablelabel.cpp.s
.PHONY : clickablelabel.s

# target to generate assembly for a file
clickablelabel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/clickablelabel.cpp.s
.PHONY : clickablelabel.cpp.s

componentefisico.o: componentefisico.cpp.o
.PHONY : componentefisico.o

# target to build an object file
componentefisico.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/componentefisico.cpp.o
.PHONY : componentefisico.cpp.o

componentefisico.i: componentefisico.cpp.i
.PHONY : componentefisico.i

# target to preprocess a source file
componentefisico.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/componentefisico.cpp.i
.PHONY : componentefisico.cpp.i

componentefisico.s: componentefisico.cpp.s
.PHONY : componentefisico.s

# target to generate assembly for a file
componentefisico.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/componentefisico.cpp.s
.PHONY : componentefisico.cpp.s

componentesalud.o: componentesalud.cpp.o
.PHONY : componentesalud.o

# target to build an object file
componentesalud.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/componentesalud.cpp.o
.PHONY : componentesalud.cpp.o

componentesalud.i: componentesalud.cpp.i
.PHONY : componentesalud.i

# target to preprocess a source file
componentesalud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/componentesalud.cpp.i
.PHONY : componentesalud.cpp.i

componentesalud.s: componentesalud.cpp.s
.PHONY : componentesalud.s

# target to generate assembly for a file
componentesalud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/componentesalud.cpp.s
.PHONY : componentesalud.cpp.s

enemigo.o: enemigo.cpp.o
.PHONY : enemigo.o

# target to build an object file
enemigo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/enemigo.cpp.o
.PHONY : enemigo.cpp.o

enemigo.i: enemigo.cpp.i
.PHONY : enemigo.i

# target to preprocess a source file
enemigo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/enemigo.cpp.i
.PHONY : enemigo.cpp.i

enemigo.s: enemigo.cpp.s
.PHONY : enemigo.s

# target to generate assembly for a file
enemigo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/enemigo.cpp.s
.PHONY : enemigo.cpp.s

entidad.o: entidad.cpp.o
.PHONY : entidad.o

# target to build an object file
entidad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/entidad.cpp.o
.PHONY : entidad.cpp.o

entidad.i: entidad.cpp.i
.PHONY : entidad.i

# target to preprocess a source file
entidad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/entidad.cpp.i
.PHONY : entidad.cpp.i

entidad.s: entidad.cpp.s
.PHONY : entidad.s

# target to generate assembly for a file
entidad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/entidad.cpp.s
.PHONY : entidad.cpp.s

grafomapa.o: grafomapa.cpp.o
.PHONY : grafomapa.o

# target to build an object file
grafomapa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/grafomapa.cpp.o
.PHONY : grafomapa.cpp.o

grafomapa.i: grafomapa.cpp.i
.PHONY : grafomapa.i

# target to preprocess a source file
grafomapa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/grafomapa.cpp.i
.PHONY : grafomapa.cpp.i

grafomapa.s: grafomapa.cpp.s
.PHONY : grafomapa.s

# target to generate assembly for a file
grafomapa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/grafomapa.cpp.s
.PHONY : grafomapa.cpp.s

jugador.o: jugador.cpp.o
.PHONY : jugador.o

# target to build an object file
jugador.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/jugador.cpp.o
.PHONY : jugador.cpp.o

jugador.i: jugador.cpp.i
.PHONY : jugador.i

# target to preprocess a source file
jugador.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/jugador.cpp.i
.PHONY : jugador.cpp.i

jugador.s: jugador.cpp.s
.PHONY : jugador.s

# target to generate assembly for a file
jugador.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/jugador.cpp.s
.PHONY : jugador.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

mapawidget.o: mapawidget.cpp.o
.PHONY : mapawidget.o

# target to build an object file
mapawidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/mapawidget.cpp.o
.PHONY : mapawidget.cpp.o

mapawidget.i: mapawidget.cpp.i
.PHONY : mapawidget.i

# target to preprocess a source file
mapawidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/mapawidget.cpp.i
.PHONY : mapawidget.cpp.i

mapawidget.s: mapawidget.cpp.s
.PHONY : mapawidget.s

# target to generate assembly for a file
mapawidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/mapawidget.cpp.s
.PHONY : mapawidget.cpp.s

menuopciones.o: menuopciones.cpp.o
.PHONY : menuopciones.o

# target to build an object file
menuopciones.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/menuopciones.cpp.o
.PHONY : menuopciones.cpp.o

menuopciones.i: menuopciones.cpp.i
.PHONY : menuopciones.i

# target to preprocess a source file
menuopciones.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/menuopciones.cpp.i
.PHONY : menuopciones.cpp.i

menuopciones.s: menuopciones.cpp.s
.PHONY : menuopciones.s

# target to generate assembly for a file
menuopciones.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/menuopciones.cpp.s
.PHONY : menuopciones.cpp.s

nivelraicesolvidadas.o: nivelraicesolvidadas.cpp.o
.PHONY : nivelraicesolvidadas.o

# target to build an object file
nivelraicesolvidadas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/nivelraicesolvidadas.cpp.o
.PHONY : nivelraicesolvidadas.cpp.o

nivelraicesolvidadas.i: nivelraicesolvidadas.cpp.i
.PHONY : nivelraicesolvidadas.i

# target to preprocess a source file
nivelraicesolvidadas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/nivelraicesolvidadas.cpp.i
.PHONY : nivelraicesolvidadas.cpp.i

nivelraicesolvidadas.s: nivelraicesolvidadas.cpp.s
.PHONY : nivelraicesolvidadas.s

# target to generate assembly for a file
nivelraicesolvidadas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/nivelraicesolvidadas.cpp.s
.PHONY : nivelraicesolvidadas.cpp.s

pantallacarga.o: pantallacarga.cpp.o
.PHONY : pantallacarga.o

# target to build an object file
pantallacarga.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/pantallacarga.cpp.o
.PHONY : pantallacarga.cpp.o

pantallacarga.i: pantallacarga.cpp.i
.PHONY : pantallacarga.i

# target to preprocess a source file
pantallacarga.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/pantallacarga.cpp.i
.PHONY : pantallacarga.cpp.i

pantallacarga.s: pantallacarga.cpp.s
.PHONY : pantallacarga.s

# target to generate assembly for a file
pantallacarga.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/pantallacarga.cpp.s
.PHONY : pantallacarga.cpp.s

pantallainicio.o: pantallainicio.cpp.o
.PHONY : pantallainicio.o

# target to build an object file
pantallainicio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/pantallainicio.cpp.o
.PHONY : pantallainicio.cpp.o

pantallainicio.i: pantallainicio.cpp.i
.PHONY : pantallainicio.i

# target to preprocess a source file
pantallainicio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/pantallainicio.cpp.i
.PHONY : pantallainicio.cpp.i

pantallainicio.s: pantallainicio.cpp.s
.PHONY : pantallainicio.s

# target to generate assembly for a file
pantallainicio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/pantallainicio.cpp.s
.PHONY : pantallainicio.cpp.s

sprite.o: sprite.cpp.o
.PHONY : sprite.o

# target to build an object file
sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/sprite.cpp.o
.PHONY : sprite.cpp.o

sprite.i: sprite.cpp.i
.PHONY : sprite.i

# target to preprocess a source file
sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/sprite.cpp.i
.PHONY : sprite.cpp.i

sprite.s: sprite.cpp.s
.PHONY : sprite.s

# target to generate assembly for a file
sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/sprite.cpp.s
.PHONY : sprite.cpp.s

tranformacion.o: tranformacion.cpp.o
.PHONY : tranformacion.o

# target to build an object file
tranformacion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/tranformacion.cpp.o
.PHONY : tranformacion.cpp.o

tranformacion.i: tranformacion.cpp.i
.PHONY : tranformacion.i

# target to preprocess a source file
tranformacion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/tranformacion.cpp.i
.PHONY : tranformacion.cpp.i

tranformacion.s: tranformacion.cpp.s
.PHONY : tranformacion.s

# target to generate assembly for a file
tranformacion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/tranformacion.cpp.s
.PHONY : tranformacion.cpp.s

tutorialscene.o: tutorialscene.cpp.o
.PHONY : tutorialscene.o

# target to build an object file
tutorialscene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/tutorialscene.cpp.o
.PHONY : tutorialscene.cpp.o

tutorialscene.i: tutorialscene.cpp.i
.PHONY : tutorialscene.i

# target to preprocess a source file
tutorialscene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/tutorialscene.cpp.i
.PHONY : tutorialscene.cpp.i

tutorialscene.s: tutorialscene.cpp.s
.PHONY : tutorialscene.s

# target to generate assembly for a file
tutorialscene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/tutorialscene.cpp.s
.PHONY : tutorialscene.cpp.s

videointro.o: videointro.cpp.o
.PHONY : videointro.o

# target to build an object file
videointro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/videointro.cpp.o
.PHONY : videointro.cpp.o

videointro.i: videointro.cpp.i
.PHONY : videointro.i

# target to preprocess a source file
videointro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/videointro.cpp.i
.PHONY : videointro.cpp.i

videointro.s: videointro.cpp.s
.PHONY : videointro.s

# target to generate assembly for a file
videointro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProyectDeimos2.dir/build.make CMakeFiles/ProyectDeimos2.dir/videointro.cpp.s
.PHONY : videointro.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ProyectDeimos2_autogen"
	@echo "... ProyectDeimos2_autogen_timestamp_deps"
	@echo "... ProyectDeimos2"
	@echo "... ObjetosYColisiones.o"
	@echo "... ObjetosYColisiones.i"
	@echo "... ObjetosYColisiones.s"
	@echo "... ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.o"
	@echo "... ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.i"
	@echo "... ProyectDeimos2_autogen/EWIEGA46WW/qrc_resources.s"
	@echo "... ProyectDeimos2_autogen/mocs_compilation.o"
	@echo "... ProyectDeimos2_autogen/mocs_compilation.i"
	@echo "... ProyectDeimos2_autogen/mocs_compilation.s"
	@echo "... clickablelabel.o"
	@echo "... clickablelabel.i"
	@echo "... clickablelabel.s"
	@echo "... componentefisico.o"
	@echo "... componentefisico.i"
	@echo "... componentefisico.s"
	@echo "... componentesalud.o"
	@echo "... componentesalud.i"
	@echo "... componentesalud.s"
	@echo "... enemigo.o"
	@echo "... enemigo.i"
	@echo "... enemigo.s"
	@echo "... entidad.o"
	@echo "... entidad.i"
	@echo "... entidad.s"
	@echo "... grafomapa.o"
	@echo "... grafomapa.i"
	@echo "... grafomapa.s"
	@echo "... jugador.o"
	@echo "... jugador.i"
	@echo "... jugador.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... mapawidget.o"
	@echo "... mapawidget.i"
	@echo "... mapawidget.s"
	@echo "... menuopciones.o"
	@echo "... menuopciones.i"
	@echo "... menuopciones.s"
	@echo "... nivelraicesolvidadas.o"
	@echo "... nivelraicesolvidadas.i"
	@echo "... nivelraicesolvidadas.s"
	@echo "... pantallacarga.o"
	@echo "... pantallacarga.i"
	@echo "... pantallacarga.s"
	@echo "... pantallainicio.o"
	@echo "... pantallainicio.i"
	@echo "... pantallainicio.s"
	@echo "... sprite.o"
	@echo "... sprite.i"
	@echo "... sprite.s"
	@echo "... tranformacion.o"
	@echo "... tranformacion.i"
	@echo "... tranformacion.s"
	@echo "... tutorialscene.o"
	@echo "... tutorialscene.i"
	@echo "... tutorialscene.s"
	@echo "... videointro.o"
	@echo "... videointro.i"
	@echo "... videointro.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

